org: cosmeticosco
app: cosmeticosco
service: cosmeticosco
frameworkVersion: "3"

custom:
  tableName: "cosmeticos-co-produtos"
  esbuild:
    bundle: true
    minify: false

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ProdutosTable, Arn]
  environment:
    USERS_TABLE: ${self:custom.tableName}

functions:
  cosmeticos-co-api:
    handler: handler.handler
    events:
      - httpApi: "*"

resources:
  Resources:
    ProdutosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: produto_id
            AttributeType: N
        KeySchema:
          - AttributeName: produto_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}